# Ansible Inventory File
# Update the IP address and key path before running playbook

[servers]
# EC2 Instance created by Terraform
# Replace INSTANCE_PUBLIC_IP with the actual IP from terraform output
INSTANCE_PUBLIC_IP ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/ec2-key.pem ansible_python_interpreter=/usr/bin/python3

[servers:vars]
ansible_port=22
ansible_connection=ssh
docker_image=phyoethutaa/student-calculator:latest
docker_container_name=calculator-app
docker_port=5000
host_port=5000
