[servers]
54.179.143.64 ansible_user=ec2-user

[servers:vars]
ansible_port=22
ansible_connection=ssh
docker_image=phyoethutaa/student-calculator:latest
docker_container_name=calculator-app
docker_port=5000
host_port=5000